import * as myModule from './js/firebase-components';
import * as myModule from './js/getFIlmDetails';
import * as myModule from './js/modalListeners';
import * as myModule from './js/modalRender';
import * as myModule from './js/onSubmit';
import * as myModule from './js/renderList';
import * as myModule from './js/renderPop';
import * as myModule from './js/searchApi';
import * as myModule from './library.js';
// import * as myModule from './js/firebase-home';
